In [141]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [142]:
f = pd.read_csv('housing.csv')
f = pd.concat([pd.Series(1, index=f.index, name='00'), f], axis=1)

In [143]:
X = f.iloc[:100,:9]
y = f.iloc[:100,9]
y = [i/100 for i in y]
theta = np.array([0.00]*len(x.columns))
theta

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [144]:

 (sum(X.iloc[:,1]*(y-X.dot(theta)))/len(x))*0.005


-4.494695509375

In [152]:
    alpha = 0.005
    k = 0
    i = 1000
    while k < i:        
        y1 = X.dot(theta)
        for c in range(0, len(X.columns)):
            theta[c] = theta[c] - (sum(X.iloc[:,1]*(y-X.dot(theta)))/len(x))*alpha
        k += 1
    theta

array([  4.59524062,   4.58162949,   6.24095456,   5.54171469,
         4.81914513, -17.01541354,   2.13782966,  -2.92835363,
         0.10119788])

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
y_pred

array([1020.64826229, 1428.34021643, 2157.39259601, 1223.60910354,
       4890.54481362, 2766.80174009, 1299.80293697, 1414.77176965,
       1453.69249063, 2636.21052749, 1697.39252725, 1777.44065746,
       1392.17519842, 1330.95558449, 1850.59410827, 1176.8018851 ,
       1406.88727869, 1148.82550866, 1559.47062897, 2048.40549419])

In [155]:
y_check = y_pred - y_test
y_check

array([-3.54351738e+02,  4.56340216e+02,  2.69392596e+02, -4.01390896e+02,
        1.30554481e+03, -6.46198260e+02, -4.19197063e+02,  3.65771770e+02,
       -3.54631751e+03,  2.52105275e+01,  6.00392527e+02,  3.77440657e+02,
       -2.32824802e+02,  2.88955584e+02,  2.96594108e+02,  9.38018851e+01,
        2.81887279e+02, -3.17449134e+00,  5.62470629e+02, -7.66594506e+02])

In [156]:
y_predict = X_test.dot(theta)
print(y_predict,y_test)

91     1199.196674
35     1454.581394
43     1528.800059
80     -234.235317
1     16990.653638
3      2662.019625
50    -3304.440782
33     2348.716944
89      439.037849
9      6267.369487
34     4159.365046
15     1257.028565
87    -1767.849668
53     1377.722325
40     1729.027541
77     2402.897771
81      255.049471
31     3365.665628
23     3241.323356
10     3964.453603
dtype: float64 [1375.0, 972.0, 1888.0, 1625.0, 3585.0, 3413.0, 1719.0, 1049.0, 5000.01, 2611.0, 1097.0, 1400.0, 1625.0, 1042.0, 1554.0, 1083.0, 1125.0, 1152.0, 997.0, 2815.0]
