In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
docs=['Music is a pleasant sound which is a combination of melodies and harmony and which soothes you.',
      'The music is not in the notes, but in the silence between.',
      'Cricket is a game of class, character and commitment.',
      'A person who knows music is a Musician.',
      'A cricket match consists of two competing teams with their playing eleven.',
      'Youngsters can be seen with their bats and balls playing cricket in every nook and corner of the country.',
      'Music may also refer to the art of composing such pleasant sounds with the help of the various musical instruments.']
label = ['music','music','cricket','music','cricket','cricket','music']

In [3]:
dframe = pd.DataFrame(list(zip(docs,label)),columns=['docs','label'])

In [4]:
dframe

docs    label
0  Music is a pleasant sound which is a combinati...    music
1  The music is not in the notes, but in the sile...    music
2  Cricket is a game of class, character and comm...  cricket
3            A person who knows music is a Musician.    music
4  A cricket match consists of two competing team...  cricket
5  Youngsters can be seen with their bats and bal...  cricket
6  Music may also refer to the art of composing s...    music

In [5]:
train,test=dframe.iloc[:5,:],dframe.iloc[5:,:]

In [6]:
test

docs    label
5  Youngsters can be seen with their bats and bal...  cricket
6  Music may also refer to the art of composing s...    music

In [7]:
train

docs    label
0  Music is a pleasant sound which is a combinati...    music
1  The music is not in the notes, but in the sile...    music
2  Cricket is a game of class, character and comm...  cricket
3            A person who knows music is a Musician.    music
4  A cricket match consists of two competing team...  cricket

In [8]:
train['tag']=train['label'].map({'music':0,'cricket':1})
train

C:\Users\vaibhav goel\AppData\Local\Temp\ipykernel_10220\53122504.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['tag']=train['label'].map({'music':0,'cricket':1})


docs    label  tag
0  Music is a pleasant sound which is a combinati...    music    0
1  The music is not in the notes, but in the sile...    music    0
2  Cricket is a game of class, character and comm...  cricket    1
3            A person who knows music is a Musician.    music    0
4  A cricket match consists of two competing team...  cricket    1

In [9]:
test

docs    label
5  Youngsters can be seen with their bats and bal...  cricket
6  Music may also refer to the art of composing s...    music

In [10]:
train=train.drop('label',axis=1)
train

docs  tag
0  Music is a pleasant sound which is a combinati...    0
1  The music is not in the notes, but in the sile...    0
2  Cricket is a game of class, character and comm...    1
3            A person who knows music is a Musician.    0
4  A cricket match consists of two competing team...    1

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
vec =CountVectorizer()
vec.fit(train['docs'])
vec.vocabulary_

{'music': 18,
 'is': 14,
 'pleasant': 25,
 'sound': 28,
 'which': 33,
 'combination': 5,
 'of': 22,
 'melodies': 17,
 'and': 0,
 'harmony': 12,
 'soothes': 27,
 'you': 36,
 'the': 30,
 'not': 20,
 'in': 13,
 'notes': 21,
 'but': 2,
 'silence': 26,
 'between': 1,
 'cricket': 9,
 'game': 11,
 'class': 4,
 'character': 3,
 'commitment': 6,
 'person': 23,
 'who': 34,
 'knows': 15,
 'musician': 19,
 'match': 16,
 'consists': 8,
 'two': 32,
 'competing': 7,
 'teams': 29,
 'with': 35,
 'their': 31,
 'playing': 24,
 'eleven': 10}

In [12]:
print("Dictionary : ",vec.get_feature_names())
print("Length of Dictionary : ",len(vec.get_feature_names()))

Dictionary :  ['and', 'between', 'but', 'character', 'class', 'combination', 'commitment', 'competing', 'consists', 'cricket', 'eleven', 'game', 'harmony', 'in', 'is', 'knows', 'match', 'melodies', 'music', 'musician', 'not', 'notes', 'of', 'person', 'playing', 'pleasant', 'silence', 'soothes', 'sound', 'teams', 'the', 'their', 'two', 'which', 'who', 'with', 'you']
Length of Dictionary :  37


C:\Users\vaibhav goel\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [13]:
vec2=CountVectorizer(stop_words='english')
vec2.fit(train['docs'])
print("Updated Dictionary : ",vec2.get_feature_names())
print("Updated length of dictionary : ",len(vec2.get_feature_names()))
vec2.vocabulary_

Updated Dictionary :  ['character', 'class', 'combination', 'commitment', 'competing', 'consists', 'cricket', 'game', 'harmony', 'knows', 'match', 'melodies', 'music', 'musician', 'notes', 'person', 'playing', 'pleasant', 'silence', 'soothes', 'sound', 'teams']
Updated length of dictionary :  22


{'music': 12,
 'pleasant': 17,
 'sound': 20,
 'combination': 2,
 'melodies': 11,
 'harmony': 8,
 'soothes': 19,
 'notes': 14,
 'silence': 18,
 'cricket': 6,
 'game': 7,
 'class': 1,
 'character': 0,
 'commitment': 3,
 'person': 15,
 'knows': 9,
 'musician': 13,
 'match': 10,
 'consists': 5,
 'competing': 4,
 'teams': 21,
 'playing': 16}

In [14]:
x_vectors=vec2.transform(train['docs'])
x_vectors

<5x22 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [15]:
print(vec2.get_feature_names())
x_vectors.toarray()

['character', 'class', 'combination', 'commitment', 'competing', 'consists', 'cricket', 'game', 'harmony', 'knows', 'match', 'melodies', 'music', 'musician', 'notes', 'person', 'playing', 'pleasant', 'silence', 'soothes', 'sound', 'teams']


array([[0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]],
      dtype=int64)

In [16]:
print(x_vectors)

  (0, 2)	1
  (0, 8)	1
  (0, 11)	1
  (0, 12)	1
  (0, 17)	1
  (0, 19)	1
  (0, 20)	1
  (1, 12)	1
  (1, 14)	1
  (1, 18)	1
  (2, 0)	1
  (2, 1)	1
  (2, 3)	1
  (2, 6)	1
  (2, 7)	1
  (3, 9)	1
  (3, 12)	1
  (3, 13)	1
  (3, 15)	1
  (4, 4)	1
  (4, 5)	1
  (4, 6)	1
  (4, 10)	1
  (4, 16)	1
  (4, 21)	1


In [17]:
test

docs    label
5  Youngsters can be seen with their bats and bal...  cricket
6  Music may also refer to the art of composing s...    music

In [18]:
test['tag']=test['label'].map({'music':0,'cricket':1})
test.drop('label',axis=1)
test_vectors = vec2.transform(test['docs'])
print(test_vectors.toarray())

[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]]


C:\Users\vaibhav goel\AppData\Local\Temp\ipykernel_10220\3759584639.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['tag']=test['label'].map({'music':0,'cricket':1})


In [19]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

mnb.fit(x_vectors, train['tag'] )

MultinomialNB()

In [20]:
mnb.predict_proba(test_vectors)

array([[0.17360115, 0.82639885],
       [0.90977444, 0.09022556]])

In [21]:
prediction = mnb.predict(test_vectors)
prediction

array([1, 0], dtype=int64)